### ISSUE TITLE
Issue with symbolic link after installation

### ISSUE THREAD

**Issue by nhoizey** [oncletom/letsencrypt-alwaysdata#3]
After installation and symbolic link creation, I can't run it.

`/home/nhoizey/.local/bin/` is in my `$PATH` but I can't run `update-certificate`:

```
nhoizey@ssh:~$ update-certificate
-bash: update-certificate: command not found
```

When I try with the absolute path, there's another issue:

```
nhoizey@ssh:~$ /home/nhoizey/.local/bin/update-certificate
-bash: /home/nhoizey/.local/bin/update-certificate: Too many levels of symbolic links
```

**Comment by nhoizey** [comment]
The [symbolic link is not good](https://twitter.com/alwaysdata/status/742721663352049664), but I think I followed the instructions…

**Comment by oncletom** [comment]
I am reworking it to only rely on extending the value of `$PATH`, looks safer.

**Comment by oncletom** [comment]
It should be solved by #5.

It should also be easier to install.

**Comment by nhoizey** [comment]
I'll try ASAP, thanks!

**Comment by oncletom** [comment]
I guess this one is solved now :-)

**Comment by nhoizey** [comment]
Indeed!
