### ISSUE TITLE
Can't update the certificate: "fullchain.pem: No such file or directory"

### ISSUE THREAD

**Issue by nhoizey** [oncletom/letsencrypt-alwaysdata#4]
I tried several values, but it keeps telling me `fullchain.pem` is missing.

![2016-06-15 at 10 53](https://cloud.githubusercontent.com/assets/78213/16073738/af5df1a4-32e7-11e6-88de-949e0069912c.png)

Maybe some additional logs would help…

**Comment by oncletom** [comment]
This is a mistake from mine. #5 should address it.

It basically assumed you already had generated a certificate in the past. I made its name clearer by renaming it from `fullchain.pem` to `certificate.pem` (as well as `key.pem` to `private-key.pem`).

**Comment by nhoizey** [comment]
It works! \o/

Thanks!
