### ISSUE TITLE
Why sometimes use `/home/$USER` and sometimes `$HOME`?

### ISSUE THREAD

**Issue by nhoizey** [oncletom/letsencrypt-alwaysdata#6]
Maybe a silly question with an obvious (not for me) answer… ;-)

**Comment by oncletom** [comment]
Ah, good question actually!

You can change your SSH home directory in the admin console so I wanted to have explanations which could work either ways. `/home/$USER` contains a few folders, including `www` which is web accessible – and should only expose the ACME challenges.

I used `/home/$USER` in the rewrite of the script and `$HOME` should be replaced by the former.

**Comment by nhoizey** [comment]
Ok, it makes sense!
