### ISSUE TITLE
Certificate is created, how to push to API?

### ISSUE THREAD

**Issue by borisschapira** [oncletom/letsencrypt-alwaysdata#7]
Hello! Thanks for your script, it's very useful. 

Unfortunately, some idiots like me fails at defining the ALWAYSDATA_API_AUTH an get themself into the situation where:

* certificate is well created and stored in the folder (yeah!)
* certificate is not push to alwaysdata through the API (error 401 - unauthorized)

After having defined the good ALWAYSDATA_API_AUTH, can I use the script just to ask a push to the alwaysdata API ?

**Comment by borisschapira** [comment]
I've removed the generated files, and relaunch the certificate creation.

**Comment by oncletom** [comment]
👍
