### ISSUE TITLE
"No module named pip"

### ISSUE THREAD

**Issue by rraallvv** [oncletom/letsencrypt-alwaysdata#9]
I get the error "No module named pip" via SSH connection to the server
`python2.7 -m pip install --user git+https://github.com/kuba/simp_le`

**Comment by fvsch** [comment]
Same issue, and I fixed it by [installing pip locally](http://pip.readthedocs.io/en/stable/installing/) like this:

```
curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
python2.7 get-pip.py --user
```

**Comment by oncletom** [comment]
Ah I skipped this one, sorry folks!

I don't know enough about python to help further up on this – I thought `pip` was installed on all AD shared hosting. I guess that's a question you should ask on their [forum](http://forum.alwaysdata.com/). Usually they reply quickly if not instantly :-)

**Comment by rraallvv** [comment]
Thanks for all the info.

**Comment by DirtyF** [comment]
FYI There's ongoing work and Alwaysdata just [announced](https://blog.alwaysdata.com/fr/2016/10/27/a-la-decouverte-de-notre-nouveau-reverse-proxy-alproxy-5/) that composer, pip, gem or npm will soon be natively supported.
